spring.application.name=study
spring.h2.console.enabled=true
spring.datasource.url=jdbc:mysql://localhost:3306/paydb
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1234
